import fs from 'fs';
import path from 'path';
import { Readability } from '@mozilla/readability';
import { JSDOM } from 'jsdom';
import TurndownService from 'turndown';

async function indexUrl(url) {
  try {
    const urlObj = new URL(url);
    if (urlObj.hostname.includes('wikipedia.org')) {
      throw new Error('Scraping Wikipedia is not allowed to prevent excessive load.');
    }
    
    console.log(`Indexing URL: ${url}`);
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch ${url}: ${response.statusText}`);
    }
    const html = await response.text();

    const dom = new JSDOM(html, { url });
    const reader = new Readability(dom.window.document);
    const article = reader.parse();

    if (!article) {
      throw new Error('Failed to extract content from the page.');
    }

    const turndownService = new TurndownService({
      headingStyle: 'atx',
      codeBlockStyle: 'fenced'
    });
    
    const markdown = turndownService.turndown(article.content);

    const domain = urlObj.hostname;
    const pathname = urlObj.pathname === '/' ? '/index' : urlObj.pathname;
    
    const targetDir = path.join('src', 'docs', domain, path.dirname(pathname));
    const fileName = `${path.basename(pathname)}.md`;
    const filePath = path.join(targetDir, fileName);

    fs.mkdirSync(targetDir, { recursive: true });
    
    // Check if domain index should exist (if > 1 file in domain dir)
    const domainDir = path.join('src', 'docs', domain);
    const domainIndexExists = fs.existsSync(path.join(domainDir, '_index.md'));
    
    let instruction = '';
    if (domainIndexExists) {
        instruction = `> 💡 **Tip**: Explore all indexed documents for **${domain}** in the [Domain Index](./_index.md).\n\n---\n\n`;
    }

    const content = `---
title: ${article.title}
source: ${url}
author: ${article.byline || 'Unknown'}
excerpt: ${article.excerpt || ''}
---

${instruction}# ${article.title}

${markdown}
`;

    fs.writeFileSync(filePath, content);
    console.log(`Successfully indexed to: ${filePath}`);
    
    // Update domain index
    updateDomainIndex(domain);
    
    return filePath;
  } catch (error) {
    console.error(`Error indexing ${url}:`, error.message);
    process.exit(1);
  }
}

function updateDomainIndex(domain) {
    const domainDir = path.join('src', 'docs', domain);
    const files = [];
    
    function walk(dir) {
        const list = fs.readdirSync(dir);
        list.forEach(file => {
            const fullPath = path.join(dir, file);
            const stat = fs.statSync(fullPath);
            if (stat.isDirectory()) {
                walk(fullPath);
            } else if (file.endsWith('.md') && file !== '_index.md') {
                const content = fs.readFileSync(fullPath, 'utf-8');
                const titleMatch = content.match(/title:\s*(.*)/);
                const relativePath = path.relative(domainDir, fullPath);
                files.push({
                    title: titleMatch ? titleMatch[1] : file,
                    path: `./${relativePath}`
                });
            }
        });
    }

    walk(domainDir);

    if (files.length > 1) {
        const indexContent = `---
title: Index of ${domain}
---

# 📚 Knowledge Index for ${domain}

This is a generated index of all documentation resources retrieved from **${domain}**.

${files.map(f => `- [${f.title}](${f.path})`).join('\n')}

---
*Generated by MDPEDIA — Knowledge for the AI Era*
`;
        fs.writeFileSync(path.join(domainDir, '_index.md'), indexContent);
        console.log(`Domain index updated for ${domain}`);

        // Patch existing files in this domain to include the instruction if they don't have it
        patchFilesWithIndexInstruction(domain, domainDir);
    }
}

function patchFilesWithIndexInstruction(domain, domainDir) {
    function walk(dir) {
        const list = fs.readdirSync(dir);
        list.forEach(file => {
            const fullPath = path.join(dir, file);
            const stat = fs.statSync(fullPath);
            if (stat.isDirectory()) {
                walk(fullPath);
            } else if (file.endsWith('.md') && file !== '_index.md') {
                let content = fs.readFileSync(fullPath, 'utf-8');
                const instruction = `> 💡 **Tip**: Explore all indexed documents for **${domain}** in the [Domain Index](./_index.md).`;
                
                if (!content.includes('[Domain Index]')) {
                    // Inject after frontmatter
                    const fmEndIndex = content.indexOf('---', 4);
                    if (fmEndIndex !== -1) {
                        const postFm = content.slice(fmEndIndex + 3);
                        content = content.slice(0, fmEndIndex + 3) + `\n\n${instruction}\n\n---` + postFm;
                        fs.writeFileSync(fullPath, content);
                    }
                }
            }
        });
    }
    walk(domainDir);
}

const url = process.argv[2];
if (!url) {
  console.error('Usage: node index-url.js <URL>');
  process.exit(1);
}

indexUrl(url);
